FROM python:3.8 as compile-image

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
COPY requirements.txt .
RUN /opt/venv/bin/python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt
RUN apt-get update
RUN apt-get install -y ffmpeg libsm6 libxext6 
RUN apt-get install -y openssh-server
COPY . /backoffice
EXPOSE 7070
CMD ["uvicorn", "backoffice.main:app", "--port", "7070", "--host", "0.0.0.0", "--reload"]

# build docker
#   docker build -t face-reco-backoffice .
# run docker
#   docker run -p 7070:7070 face-reco-backoffice